[versions]
agp = "8.1.4"
kotlin = "1.9.22"
androidx-compose-compiler = "1.5.8"
compose-full = "1.6.0"
material = "1.12.0-alpha03"
activity-compose = "1.9.0-alpha03"
kotlinx-coroutines-core = "1.8.0"
koin-core = "3.6.0-wasm-alpha2"
koin-compose = "3.6.0-wasm-alpha2"
precompose = "1.6.0-beta02"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin-core" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin-compose" }
precompose = { group = "moe.tlaster", name = "precompose", version.ref = "precompose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeFull = { id = "org.jetbrains.compose", version.ref = "compose-full" }
