[versions]
activity-compose = "1.9.0-alpha03"
foundation = "1.7.0-alpha02"
material = "1.7.0-alpha02"
navigation-compose = "2.8.0-alpha02"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

[plugins]