[versions]
runtime = "1.7.0-alpha02"
material = "1.7.0-alpha02"
ui-util = "1.7.0-alpha02"
activity-compose = "1.9.0-alpha03"
navigation-compose = "2.8.0-alpha02"
lifecycle-viewmodel-compose = "2.8.0-alpha01"
lifecycle-runtime-compose = "2.8.0-alpha01"

[libraries]
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
androidx-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "ui-util" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }

[plugins]